ALTER TABLE person MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE address MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE region MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE attendance_map MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE team_type MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE team_map MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE small_group MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE small_group_map MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE foodserving_map MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE sunday_school_class_type MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE sunday_school_map MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE child_map MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE song MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE song_tag MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE song_tag_map MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE worship_set MODIFY COLUMN id INT AUTO_INCREMENT;

ALTER TABLE worship_set_map MODIFY COLUMN id INT AUTO_INCREMENT;
